export const CART_ITEM_ADDED = 'cart/CART_ITEM_ADDED';
export const CART_ITEM_REMOVED = 'cart/CART_ITEM_ADDED';
export const CHECKOUT_REQUESTED = 'cart/CART_CHECKOUT_REQUESTED';
export const CHECKOUT_SUCCESSFUL = 'cart/CART_CHECKOUT_SUCCESS';
export const CHECKOUT_FAILED = 'cart/CART_CHECKOUT_FAILURE';
