export const EVENT_LOAD_REQUESTED = 'EVENT_LOAD_REQUESTED';
export const EVENT_LOAD_COMPLETED = 'EVENT_LOAD_COMPLETED';
export const EVENT_STARTED = 'EVENT_STARTED';
export const EVENT_ENDED = 'EVENT_ENDED';
export const EVENT_ACCESS_GRANTED = 'EVENT_ENDED';
